global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: products-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - products-api:80

  - job_name: stock-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - stock-api:8080

  - job_name: web
    metrics_path: /metrics
    static_configs:
      - targets:
          - web:80